00_tensorflow_fundamentals

# In this notebook, we are going to cover some of the most fundamental concepts of tensors using Tensorflow

More specifically, we're going to cover:
* Intro to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with Tensorflow or TPUS
* Excercies to try

## Intro to tensors

In [3]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [9]:
# Creating tensors with t.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [10]:
# check the number of dimension of a tensor (ndim - num of dim)
scalar.ndim


0

In [11]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
# check the dimension of vector
vector.ndim

1

In [14]:
# creat a matrix, more than 1 dimension
matrix =  tf.constant([[10, 7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [15]:
matrix.ndim

2

In [17]:
# create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8.,9.]], dtype=tf.float16) # specify data type

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [18]:
another_matrix.ndim

2

In [20]:
# let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [21]:
tensor.ndim

3

What we have created so far
* Scalar - single number
* Vector - a number with direct ( wind speed and direction)
* Matrix - 2d array of numbers
* Tensor - n-dim array of numbers, where n can be any number 0-dim  tensor is scalar